title: David's Web Site
theme: minima
description: This is my personal web site.
url: https://davidmc1948.github.io
repo: https://github.com/DavidMc1948/davidmc1948.github.io
twitter_username: jekyllrb
facebook_username: jekyllrb
github_username:  jekyll

header_pages:
  - about.md
  - index.html
  - pagelist.md
  - pdf_file_list.md

defaults:
    - scope:
        path: "assets/pdf"
      values:
        image: true
