title: David's Web Site
theme: minima
description: This is my personal web site.
url: https://davidmc1948.github.io
repo: https://github.com/DavidMc1948/davidmc1948.github.io

defaults:
  - scope:
      path: "assets/pdf"
    values:
      image: true
